(() => {
"use strict";
const SUPABASE_URL=window.UMAR_SUPABASE_URL; const SUPABASE_KEY=window.UMAR_SUPABASE_KEY; const supabase=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const STORAGE_KEY="umar-messenger-v4";
const palette=["orange","blue","green","purple"];
const initialChats=[
{id:"ali",name:"Али",color:"orange",status:"в сети",unread:2,updated:"20:14",messages:[{mine:false,text:"Привет! 👋",time:"20:12"},{mine:false,text:"Как дела?",time:"20:13"},{mine:true,text:"Всё хорошо. Увидимся завтра!",time:"20:14",status:"✓✓"}]},
{id:"muhammad",name:"Мухаммад",color:"blue",status:"был недавно",unread:0,updated:"19:48",messages:[{mine:false,text:"Отправил тебе файл",time:"19:48"}]}
];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const authScreen=$("#authScreen"),authViews=$("#authViews"),appShell=$("#appShell");
let state=loadState(),deferredInstallPrompt=null;
function loadState(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||{}}catch{return{}}}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function initials(name){return name.trim().split(/\s+/).map(x=>x[0]).slice(0,2).join("").toUpperCase()||"U"}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
async function profileFor(userId){const {data,error}=await supabase.from("Users").select("id,email,username,display_name,avatar_url,auth_user_id").eq("auth_user_id",userId).maybeSingle();if(error)throw error;return data}
function showAuth(mode="login"){
 authScreen.hidden=false; appShell.hidden=true;
 authViews.innerHTML=mode==="login"?`
<h1 class="auth-title">Вход</h1><p class="auth-subtitle">Войдите в Umar Messenger со своим аккаунтом.</p>
<form class="auth-form" id="loginForm"><label class="auth-label">Email<input class="auth-input" id="loginEmail" type="email" autocomplete="email" required></label><label class="auth-label">Пароль<input class="auth-input" id="loginPassword" type="password" autocomplete="current-password" required></label><div class="auth-error" id="authError"></div><button class="auth-button">Войти</button><button class="auth-link" id="goSignup" type="button">Еще нет аккаунта? Зарегистрироваться</button></form>`:`
<h1 class="auth-title">Регистрация</h1><p class="auth-subtitle">Создайте аккаунт. Email и никнейм должны быть уникальными.</p>
<form class="auth-form" id="signupForm"><label class="auth-label">Email<input class="auth-input" id="signupEmail" type="email" autocomplete="email" required></label><label class="auth-label">Пароль<input class="auth-input" id="signupPassword" type="password" minlength="8" autocomplete="new-password" required></label><label class="auth-label">Повторите пароль<input class="auth-input" id="signupPassword2" type="password" minlength="8" autocomplete="new-password" required></label><label class="auth-label">Желаемый никнейм<input class="auth-input" id="signupUsername" type="text" pattern="[a-zA-Z0-9_]{3,32}" placeholder="alex99" required></label><div class="auth-error" id="authError"></div><button class="auth-button">Создать аккаунт</button><button class="auth-link" id="goLogin" type="button">Уже есть аккаунт? Войти</button></form>`;
 if(mode==="login"){$("#goSignup").onclick=()=>showAuth("signup");$("#loginForm").onsubmit=login}else{$("#goLogin").onclick=()=>showAuth("login");$("#signupForm").onsubmit=signup}
}
function showSetup(user){
 authScreen.hidden=false;appShell.hidden=true;
 authViews.innerHTML=`<div class="setup-avatar avatar orange" id="setupAvatar">${esc(initials(user.display_name||"U"))}</div><h1 class="auth-title">Настройте профиль</h1><p class="auth-subtitle">Это появится один раз после регистрации.</p><form class="auth-form" id="setupForm"><label class="auth-label">Имя<input class="auth-input" id="setupName" maxlength="40" value="${esc(user.display_name||"")} " required></label><div class="avatar-upload"><label>Загрузить фото<input id="setupAvatarFile" type="file" accept="image/*"></label></div><div class="auth-error" id="authError"></div><button class="auth-button">Готово</button></form>`;
 $("#setupAvatarFile").onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{$("#setupAvatar").style.backgroundImage="url('"+r.result+"')";$("#setupAvatar").style.backgroundSize="cover";$("#setupAvatar").textContent=""};r.readAsDataURL(f)};
 $("#setupForm").onsubmit=async e=>{e.preventDefault();const err=$("#authError");err.textContent="";try{const {data:auth}=await supabase.auth.getUser();if(!auth.user)throw new Error("Сессия закончилась. Войдите снова.");const {data,error}=await supabase.from("Users").update({display_name:$("#setupName").value.trim()}).eq("auth_user_id",auth.user.id).select("id,email,username,display_name,avatar_url,auth_user_id").single();if(error)throw error;state.user=data;state.setupDone=true;saveState();startApp()}catch(x){err.textContent=x.message}}
}
async function login(e){e.preventDefault();const err=$("#authError");err.textContent="";try{const {data,error}=await supabase.auth.signInWithPassword({email:$("#loginEmail").value.trim().toLowerCase(),password:$("#loginPassword").value});if(error)throw error;const profile=await profileFor(data.user.id);if(!profile)throw new Error("Профиль пользователя не найден.");state.user=profile;saveState();profile.display_name?.trim()?startApp():showSetup(profile)}catch(x){err.textContent=x.message||"Не удалось войти."}}
async function signup(e){e.preventDefault();const err=$("#authError"),p=$("#signupPassword").value,p2=$("#signupPassword2").value,username=$("#signupUsername").value.trim();if(p!==p2){err.textContent="Пароли не совпадают";return}if(!/^[a-zA-Z0-9_]{3,32}$/.test(username)){err.textContent="Никнейм: 3–32 символа, только латиница, цифры и _.";return}try{const {data:existing,error:ce}=await supabase.from("Users").select("id").eq("username",username).maybeSingle();if(ce)throw ce;if(existing){err.textContent="Этот никнейм уже занят.";return}const {data,error}=await supabase.auth.signUp({email:$("#signupEmail").value.trim().toLowerCase(),password:p});if(error)throw error;if(!data.session){err.textContent="Аккаунт создан. Подтвердите email, если это включено в Supabase, затем войдите.";return}const {data:updated,error:ue}=await supabase.from("Users").update({username}).eq("auth_user_id",data.user.id).select("id,email,username,display_name,avatar_url,auth_user_id").single();if(ue){if(ue.code==="23505")throw new Error("Этот никнейм уже занят.");throw ue}if(!updated)throw new Error("Профиль ещё создаётся. Попробуйте войти через несколько секунд.");state.user=updated;saveState();showSetup(updated)}catch(x){err.textContent=x.message||"Не удалось зарегистрироваться."}}
function startApp(){authScreen.hidden=true;appShell.hidden=false;state.chats=state.chats?.length?state.chats:structuredClone(initialChats);state.selected=state.selected||state.chats[0]?.id;state.filter=state.filter||"all";state.theme=state.theme||"dark";state.profile=state.profile||{name:state.user?.display_name||"Umar",status:"в сети"};state.notifications=state.notifications!==false;state.lastSeen=state.lastSeen!==false;state.readReceipts=state.readReceipts!==false;document.documentElement.dataset.theme=state.theme;renderAll()}
function renderChats(){const list=$("#chatList"),q=$("#searchInput").value.trim().toLowerCase();list.innerHTML="";state.chats.filter(c=>state.filter==="all"||c.unread>0).filter(c=>c.name.toLowerCase().includes(q)).forEach(c=>{const el=document.createElement("article");el.className="chat"+(c.id===state.selected?" is-active":"");el.dataset.chatId=c.id;el.tabIndex=0;el.innerHTML=`<div class="avatar ${c.color}">${esc(initials(c.name))}</div><div class="chat-copy"><div class="chat-top"><strong>${esc(c.name)}</strong><time>${esc(c.updated)}</time></div><div class="chat-bottom"><span class="chat-preview">${esc(c.messages.at(-1)?.text||"Новый чат")}</span>${c.unread?`<span class="unread">${c.unread}</span>`:""}</div></div>`;list.appendChild(el)})}
function selectedChat(){return state.chats.find(c=>c.id===state.selected)||state.chats[0]}
function renderConversation(){const c=selectedChat();if(!c)return;$("#headerName").textContent=c.name;$("#headerStatus").textContent=c.status;$("#headerAvatar").textContent=initials(c.name);$("#headerAvatar").className="avatar "+c.color;$("#detailsName").textContent=c.name;$("#detailsStatus").textContent=c.status;$("#detailsAvatar").textContent=initials(c.name);$("#detailsAvatar").className="details-avatar avatar "+c.color;$("#messages").innerHTML='<div class="day">Сегодня</div>'+c.messages.map(m=>`<div class="message ${m.mine?"mine":""}"><div class="bubble">${esc(m.text)}<span class="message-meta">${esc(m.time)} ${m.mine?esc(m.status||"✓"):""}</span></div></div>`).join("");requestAnimationFrame(()=>$("#messages").scrollTop=$("#messages").scrollHeight)}
function renderAll(){renderChats();renderConversation();syncSettings()}
function selectChat(id){if(!state.chats.some(c=>c.id===id))return;state.selected=id;selectedChat().unread=0;saveState();renderAll();$("#conversation").classList.add("is-open")}
function sendMessage(v){v=v.trim();if(!v)return;const c=selectedChat(),time=new Date().toLocaleTimeString("ru-RU",{hour:"2-digit",minute:"2-digit"});c.messages.push({mine:true,text:v,time,status:"✓"});c.updated=time;saveState();renderAll();$("#messageInput").value=""}
function openSettings(){const d=$("#settingsDrawer");d.hidden=false;requestAnimationFrame(()=>d.classList.add("is-open"))}function closeSettings(){const d=$("#settingsDrawer");d.classList.remove("is-open");setTimeout(()=>d.hidden=true,220)}
function openSettingsModal(t,s,b){$("#settingsModalTitle").textContent=t;$("#settingsModalSubtitle").textContent=s;$("#settingsModalBody").innerHTML=b;$("#settingsModal").hidden=false}function closeSettingsModal(){$("#settingsModal").hidden=true}
function syncSettings(){$("#notificationState").textContent=state.notifications?"Включены":"Выключены";$("#dataState").textContent=(state.chats?.length||0)+" чата(ов) на этом устройстве";$("#appearanceButton small").textContent=state.theme==="light"?"Светлая тема":"Тёмная тема";$("#privacyButton small").textContent=state.lastSeen?"Последний визит виден":"Скрыт";$(".settings-profile strong").textContent=state.profile?.name||"Umar";$(".settings-profile span").textContent=state.profile?.status||"в сети"}
function installApp(){if(deferredInstallPrompt){deferredInstallPrompt.prompt();deferredInstallPrompt.userChoice.finally(()=>deferredInstallPrompt=null);return}openSettingsModal("Установка Umar","Добавьте сайт как приложение",'<div class="about-app"><div class="about-logo">U</div><strong>Umar Messenger</strong><p>В Chrome откройте меню браузера и выберите «Установить Umar Messenger».</p></div>')}
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredInstallPrompt=e;$("#downloadAppButton strong").textContent="Установить приложение";$("#downloadAppButton small").textContent="Добавить Umar на устройство"});
window.addEventListener("appinstalled",()=>deferredInstallPrompt=null);
$("#chatList").onclick=e=>{const x=e.target.closest(".chat");if(x)selectChat(x.dataset.chatId)};$("#searchInput").oninput=renderChats;$$(".filter").forEach(b=>b.onclick=()=>{$$(".filter").forEach(x=>x.classList.remove("is-active"));b.classList.add("is-active");state.filter=b.dataset.filter;saveState();renderChats()});
$("#composer").onsubmit=e=>{e.preventDefault();sendMessage($("#messageInput").value)};$("#backButton").onclick=()=>$("#conversation").classList.remove("is-open");$("#infoButton").onclick=()=>$("#detailsPanel").classList.toggle("is-open");$("#chatSearchButton").onclick=()=>$("#searchInput").focus();
$("#profileButton").onclick=openSettings;$("#closeSettings").onclick=closeSettings;$("#settingsDrawer").onclick=e=>{if(e.target.id==="settingsDrawer")closeSettings()};$("#closeSettingsModal").onclick=closeSettingsModal;$("#settingsModal").onclick=e=>{if(e.target.id==="settingsModal")closeSettingsModal()};
$("#deleteContactButton").onclick=()=>{const c=selectedChat();if(!c)return;$("#deleteName").textContent=c.name;$("#deleteUsername").textContent="@"+c.id.replace(/^chat-/,"");$("#deleteAvatar").textContent=initials(c.name);$("#deleteDialog").hidden=false};$("#cancelDelete").onclick=()=>$("#deleteDialog").hidden=true;$("#confirmDelete").onclick=()=>{state.chats=state.chats.filter(c=>c.id!==state.selected);state.selected=state.chats[0]?.id;$("#deleteDialog").hidden=true;saveState();renderAll()};
$("#notificationsSettingsButton").onclick=()=>{openSettingsModal("Уведомления","Управление уведомлениями",'<div class="setting-control"><div><strong>Уведомления</strong><small>Новые сообщения</small></div><button class="toggle-button is-on" id="nToggle"><span></span></button></div>');$("#nToggle").classList.toggle("is-on",state.notifications);$("#nToggle").onclick=()=>{state.notifications=!state.notifications;saveState();syncSettings();closeSettingsModal()}};
$("#appearanceButton").onclick=()=>{openSettingsModal("Оформление","Выберите тему",'<div class="theme-options"><button class="theme-option" id="darkTheme"><b>Тёмная</b><small>LOWPOLY dark</small></button><button class="theme-option" id="lightTheme"><b>Светлая</b><small>Светлая поверхность</small></button></div>');$("#"+(state.theme==="light"?"lightTheme":"darkTheme")).classList.add("is-active");$("#darkTheme").onclick=()=>{state.theme="dark";document.documentElement.dataset.theme="dark";saveState();syncSettings();closeSettingsModal()};$("#lightTheme").onclick=()=>{state.theme="light";document.documentElement.dataset.theme="light";saveState();syncSettings();closeSettingsModal()}};
$("#editProfileButton").onclick=()=>{openSettingsModal("Профиль","Ваше имя и статус",'<label class="modal-label">Имя</label><input class="modal-input" id="pName" maxlength="32"><label class="modal-label">Статус</label><input class="modal-input" id="pStatus" maxlength="60"><div class="modal-actions"><button class="secondary-button" id="pCancel">Отмена</button><button class="primary-button" id="pSave">Сохранить</button></div>');$("#pName").value=state.profile.name;$("#pStatus").value=state.profile.status;$("#pCancel").onclick=closeSettingsModal;$("#pSave").onclick=()=>{state.profile={name:$("#pName").value.trim()||"Umar",status:$("#pStatus").value.trim()||"в сети"};saveState();syncSettings();closeSettingsModal()}};
$("#privacyButton").onclick=()=>{openSettingsModal("Конфиденциальность","Кто видит активность",'<div class="setting-control"><div><strong>Последний визит</strong><small>Показывать время последнего посещения</small></div><button class="toggle-button is-on" id="lastToggle"><span></span></button></div><div class="setting-control"><div><strong>Статус прочтения</strong><small>Отметки о прочтении</small></div><button class="toggle-button is-on" id="readToggle"><span></span></button></div>');$("#lastToggle").classList.toggle("is-on",state.lastSeen);$("#readToggle").classList.toggle("is-on",state.readReceipts);$("#lastToggle").onclick=()=>{state.lastSeen=!state.lastSeen;saveState();syncSettings();$("#lastToggle").classList.toggle("is-on",state.lastSeen)};$("#readToggle").onclick=()=>{state.readReceipts=!state.readReceipts;saveState();$("#readToggle").classList.toggle("is-on",state.readReceipts)}};
$("#dataButton").onclick=()=>{openSettingsModal("Данные и хранилище","Данные этого устройства",`<div class="data-card"><strong>${state.chats.length}</strong><span>чатов сохранено локально</span></div><button class="danger-button data-clear" id="clearData">Очистить локальные данные</button>`);$("#clearData").onclick=()=>{if(confirm("Удалить локальные данные?")){localStorage.removeItem(STORAGE_KEY);location.reload()}}};
$("#downloadAppButton").onclick=installApp;$("#aboutButton").onclick=()=>openSettingsModal("О приложении","Umar Messenger",'<div class="about-app"><div class="about-logo">U</div><strong>Umar Messenger</strong><span>LOWPOLY • версия 1.0</span><p>Веб-мессенджер.</p></div>');
const emojis="😀 😃 😄 😁 😆 😂 🙂 😉 😊 😎 😍 🥰 🤗 🤔 😐 🙄 😏 😥 😮 😴 🥳 😭 😢 😤 😡 😱 🤩 😋 😜 🫡 ❤️ 🧡 💛 💚 💙 💜 🖤 🤍 💔 👍 👎 👌 ✌️ 🤝 🙏 👏 🎉 🔥 ⭐ 💯 🚀 ⚡ 🌙 ☀️ ☕ 🍕 🍔 ⚽ 🎮".split(" ");$("#emojiGrid").innerHTML=emojis.map(e=>'<button type="button" class="emoji-item">'+e+"</button>").join("");$("#emojiButton").onclick=()=>$("#emojiPicker").hidden=!$("#emojiPicker").hidden;$("#closeEmoji").onclick=()=>$("#emojiPicker").hidden=true;$("#emojiGrid").onclick=e=>{if(e.target.classList.contains("emoji-item")){$("#messageInput").value+=e.target.textContent;$("#messageInput").focus()}};
document.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();$("#searchInput").focus()}if(e.key==="Escape"){$("#emojiPicker").hidden=true;$("#settingsModal").hidden=true}});
(async()=>{const {data}=await supabase.auth.getSession();if(!data.session){showAuth("login");return}try{const profile=await profileFor(data.session.user.id);if(!profile){await supabase.auth.signOut();showAuth("login");return}state.user=profile;saveState();profile.display_name?.trim()?startApp():showSetup(profile)}catch{showAuth("login")}})();
})();